version: "3.8"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /opt/media-server/docker-services/plex/config:/config
      - /media:/media
    ports:
      - 32400:32400
    restart: unless-stopped
  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn 
    environment:
      - PUID=997
      - PGID=998
      - TZ=UTC
      - ENABLE_UFW=true #optional but useful for debugging
      - UFW_EXTRA_PORTS=9091,8989,7878,32400,3479
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=us.protonvpn.com.udp
      - OPENVPN_USERNAME=***USERNAME***
      - OPENVPN_PASSWORD=***PASSWORD***
      - LOCAL_NETWORK=***
    volumes:
      - /media/torrent/:/data
      - /opt/media-server/docker-services/transmission-openvpn/config:/config
    cap_add:
      - NET_ADMIN
    logging:
       driver: json-file
       options:
           max-size: 10m
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Bangui
    volumes:
      - /opt/media-server/docker-services/jackett/config:/config
      - /media/torrent/completed:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Bangui
      - UMASK_SET=022 #optional
    volumes:
      - /opt/media-server/docker-services/sonarr/config:/config
      - /media:/media
      - /media/torrent:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Bangui
      - UMASK_SET=022 #optional
    volumes:
      - /opt/media-server/docker-services/radarr/config:/config
      - /media:/media
      - /media/torrent/:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Bangui
      - BASE_URL=/ombi #optional
    volumes:
      - /opt/media-server/docker-services/ombi/config:/config
      - /media:/media
    ports:
      - 3579:3579
    restart: unless-stopped
