version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=nord
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_COUNTRIES=India
    ports:
      - 9117:9117
      - 8989:8989
      - 7878:7878
      - 3579:3579
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
      - 8191:8191
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /media/config/plex:/config
      - /media/media/TV Shows:/tv
      - /media/media/Movies:/movies
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Abidjan
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
#      - USER=username #optional YOU SHOULD ADD A USERNAME AND PASSWORD 
#      - PASS=password #optional
#      - WHITELIST=iplist #optional
#      - HOST_WHITELIST=dnsname list #optional
    volumes:
      - /media/config/transmission:/config
      - /media:/data
#      - /media/torrent/watch:/watch # any torrent file you put into /watch will be auto downloaded
    network_mode: "service:gluetun"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=997
      - PGID=998
      - TZ=
      - UMASK_SET=022 #optional
    volumes:
      - /media/config/sonarr:/config
      - /media:/data
    network_mode: "service:gluetun"
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=
      - UMASK_SET=022 #optional
    volumes:
      - /media/config/radarr:/config
      - /media:/data
    network_mode: "service:gluetun"
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Abidjan
    volumes:
      - /media/config/jackett:/config
      - /media:/data
    network_mode: "service:gluetun"
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Abidjan
      - BASE_URL=/ombi #optional
    volumes:
      - /media/config/ombi:/config
      - /media:/media
      - /media/torrent:/config/qBittorrent
    network_mode: "service:gluetun"
    restart: unless-stopped
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Africa/Abidjan
      - PUID=1000
      - PGID=1000
    network_mode: "service:gluetun"
    restart: unless-stopped
